
services:
  db-tech:
    image: postgres:16.1
    container_name: db-tech
    volumes:
      - tech:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
volumes:
  tech:
    external: false

