spring:
  application:
    name: tech
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tech
    username: postgres
    password: 1234

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/tech
    user: postgres
    password: 1234

server:
  port: 8080

springdoc:
  swagger-ui:
    path: "/api/doc/tech/swagger-ui.html"
  api-docs:
    path: "/api/doc/tech/api-docs"

routes:
  paths:
    tech: "/api/v1/tech"
    associate: "/api/v1/tech/associate"
    technologies-by-capability-id: "/api/v1/tech/capabilities/{capabilityId}/techs"
    delete-technologies-by-capability-ids: "/api/v1/tech-capabilities"


